version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: task-analytics-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-analytics-network

  redis:
    image: redis:7.2-alpine
    container_name: task-analytics-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - task-analytics-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-analytics-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/taskdb
      - REDIS_URL=redis://redis:6379
    networks:
      - task-analytics-network
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-analytics-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - task-analytics-network
    depends_on:
      - backend
      - mongodb
      - redis

volumes:
  mongodb_data:
  redis_data:

networks:
  task-analytics-network:
    driver: bridge