version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: task-analytics-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-analytics-network

  redis:
    image: redis:7.2-alpine
    container_name: task-analytics-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - task-analytics-network

volumes:
  mongodb_data:
  redis_data:

networks:
  task-analytics-network:
    driver: bridge