name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Lint backend code
      working-directory: ./backend
      run: npm run lint



    - name: Run backend unit tests
      working-directory: ./backend
      run: npm test
      env:
        NODE_ENV: test

    - name: Run backend tests with coverage
      working-directory: ./backend
      run: npm run test:coverage
      env:
        NODE_ENV: test

  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Lint frontend code
      working-directory: ./frontend
      run: npm run lint

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Run frontend tests with coverage
      working-directory: ./frontend
      run: npm run test:coverage

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build


  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies and run audit
      run: |
        cd backend && npm ci && npm audit --audit-level moderate
        cd ../frontend && npm ci && npm audit --audit-level moderate

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci

    - name: Run linting
      run: |
        cd backend && npm run lint
        cd ../frontend && npm run lint


  deploy-ready:
    name: Deploy Ready Check
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend, security-scan, code-quality]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build check
      run: |
        echo "✅ All tests passed"
        echo "✅ Test coverage reports generated"
        echo "✅ Security scan completed"
        echo "✅ Code quality checks passed"
        echo "🚀 Ready for deployment"